title: Battery Park
description: >- # this means to ignore newlines until "baseurl:"
  Battery is important.
baseurl: "/Battery-Park/"
url: "https://donghee1025.github.io"
github_username: donghee1025
theme: minima
plugins:
  - jekyll-feed
